### ISSUE TITLE
Add Legality to Formats

### ISSUE THREAD

**Issue by jesseflorig** [ontehfritz/www.mtgdb.info#18]
Formats is currently an array of strings containing format names. For example, Black Lotus has:

"formats":["Legacy","Vintage","Commander"]

Would be more helpful to have an array of objects with format name and legality, like so:

"formats":[
    {
        "name":"Legacy",
        "legality":"Banned"
    },
    {
        "name":"Vintage",
        "legality":"Restricted"
    },
    {
        "name":"Commander",
        "legality":"Banned"
    }
]

**Comment by ontehfritz** [comment]
A total over-site, on my behalf, it should have been this way from the beginning. DOH! I will implement this in api on the next release. Actually I bump this up and release it in the api soon! 
:+1:

**Comment by ontehfritz** [comment]
In production
