### ISSUE TITLE
Java API - SimpleDateFormatter

### ISSUE THREAD

**Issue by randy-ja** [ontehfritz/www.mtgdb.info#36]
SimpleDateFormatter in Java is not threadsafe.  Using a final static instance can create problems if someone wants to use multithreading in their application.  Instead, a new instance of SimpleDateFormatter should be used whenever it is needed.  Constants can be used for the Format itself.

Instead of
Date date = dateFormatterInput.parse(json.getString(s));
you would end up with something like 
DateFormatter sdf = new SimpleDateFormatter(DATE_FORMAT_INPUT);
Date date = sdf.parse(json.getString(s));

**Comment by ontehfritz** [comment]
https://github.com/alotau/Java-API-to-mtgdb/issues/2
