### ISSUE TITLE
Casting Cost Parser

### ISSUE THREAD

**Issue by jesseflorig** [ontehfritz/www.mtgdb.info#38]
Casting costs that only consist of a number of colorless mana are blank on the single card view.

This affects cards like "Zuran Orb" and "Emrakul, the Aeons Torn", but not "Shifting Wall".

**Comment by ontehfritz** [comment]
Sorry jesse, you will need to explain this to me in JabbR. Everything looks fine to me.

**Comment by jesseflorig** [comment]
Hey! I'll hop on in a little. I actually fixed this in my last PR after I
submitted the issue. It was more of a catch-all added to the end, but its
working well.

On Thu, Apr 10, 2014 at 7:34 AM, Fritz (Fredrick Seitz) <
notifications@github.com> wrote:

> Sorry jesse, you will need to explain this to me in JabbR. Everything
> looks fine to me.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/planeswalkers/www.mtgdb.info/issues/38#issuecomment-40068049
> .

## 

-Jesse

**Comment by jesseflorig** [comment]
:+1: This can be closed.
