### ISSUE TITLE
Yes another f!@k'in deckbuilder

### ISSUE THREAD

**Issue by ontehfritz** [ontehfritz/www.mtgdb.info#4]
Simple deck building

**Comment by jesseflorig** [comment]
+1

**Comment by ontehfritz** [comment]
Users can name their deck
Users can add description for deck
Users have an option to select cards from their collection
Users have an option to use cards they don't have in their collection
Cards the user doesn't have are indicated (will help to indicate cards they need for their collection)
Cards used in a deck will be flagged when viewing that card. This will indicate how many decks the card is used in.
Users can track wins with their deck
Users can select the colors for their deck this will filter only by those colors
Users can make their deck public, if public they can share links to their deck
Public decks can also be shown on their profile page (later search other users deck and deck dashboard of all users public decks)
Calculate mana ratios for deck, multiple algorithms
Export/Import .dec file, other file formats ...?

**Comment by ontehfritz** [comment]
Ideally support all these deck formats we will start with the most popular first: 
*.deck - MTG Studio deck
⋅ *.dek - MTG Online III deck
⋅ *.dec - MTG Online binary deck
⋅ *.txt - MTG Online text deck
⋅ *.mwDeck - Magic Workstation deck
⋅ *.txt - Wagic the Homebrew deck
⋅ *.dck - Online Play Table deck
⋅ *.dec - Apprentice deck
⋅ *.dck - Forge deck New feature
⋅ *.dck - Shandalar/Duels of the Planeswalkers/Mana Link 2.0 and 3.0 deck
⋅ *.dck - Mana deck
⋅ *.mdb - Magic Suitcase deck
⋅ *.xml - OCTGN, MTG Play, and MTG Interactive Encyclopedia deck
⋅ *.tinydeck - Tiny deck

**Comment by ontehfritz** [comment]
Dumbing things down a bit to be more manageable. See
https://github.com/planeswalkers/www.mtgdb.info/issues/62
