### ISSUE TITLE
Binder set dropdown grouping

### ISSUE THREAD

**Issue by jesseflorig** [ontehfritz/www.mtgdb.info#42]
Update the binder set dropdown to show sets in Core, Expansions, and Compilation/Anthology groups.

I should be able to take care of this.

**Comment by ontehfritz** [comment]
:+1:

**Comment by ontehfritz** [comment]
This is done right or is there more work on needed on this?

**Comment by jesseflorig** [comment]
Its good to go with the current DB structure.

On Tue, Apr 15, 2014 at 9:04 AM, Fritz (Fredrick Seitz) <
notifications@github.com> wrote:

> This is done right or is there more work on needed on this?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/planeswalkers/www.mtgdb.info/issues/42#issuecomment-40478472
> .

## 

-Jesse

**Comment by ontehfritz** [comment]
https://github.com/planeswalkers/www.mtgdb.info/issues/45

This one covers the db structure correct?

**Comment by jesseflorig** [comment]
Yep! My qualifier was referring to the non-block Expansions that are still
grouped in Compilations. That can be addressed later if there is a DB
structure change.

But it's definitely good to go for now!

On Tue, Apr 15, 2014 at 12:01 PM, Fritz (Fredrick Seitz) <
notifications@github.com> wrote:

> #45 https://github.com/planeswalkers/www.mtgdb.info/issues/45
> 
> This one covers the db structure correct?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/planeswalkers/www.mtgdb.info/issues/42#issuecomment-40500001
> .

## 

-Jesse

**Comment by ontehfritz** [comment]
:+1:
