### ISSUE TITLE
Expand Set Type & Block into distinct fields

### ISSUE THREAD

**Issue by jesseflorig** [ontehfritz/www.mtgdb.info#45]
We could optimize a lot of set related code by separating Set Type and Block into distinct fields. Set Type would be required whereas Block is optional. The proposed change would reflect the following structure:

Core
|  |- 2014 Core
|  |- 2013 Core
|  '- [...]
Expansions
|  |- Block Name
|  |  |- Set A
|  |  '- Set B
|  '- Non Block
|    |- Arabian Nights
|    |- Antiquities
|    '- [...]
Compilations/Reprints
|  '- [...]
[...]

Source: http://en.wikipedia.org/wiki/List_of_Magic:_The_Gathering_sets

**Comment by ontehfritz** [comment]
I will get this done before the pre deck builder release, to get rid of that code stink related to sets

**Comment by ontehfritz** [comment]
This is done, it is a breaking change! But it has to be done. :)
