### ISSUE TITLE
Add a public location for javadoc and other potential API docs

### ISSUE THREAD

**Issue by alotau** [ontehfritz/www.mtgdb.info#52]
I generated javadoc for the Java API.  Might be handy to make that visible somewhere on the api.mtgdb.info or www.mtgdb.info sites somewhere.

Not sure if this is the best spot for the issue, but wanted to get it somewhere before I forgot about it.

**Comment by ontehfritz** [comment]
Nice, Yeah a page for each driver/client/wrapper is the way it should be. One way to approach this is to simply make a github page for your api and I can link to it. That way you have full control of updating the page including the updates of the jar file. I will create an issue on your client repo. I think this will be the way to approach all the clients including the c# driver as well.
