### ISSUE TITLE
GET returns irrelevant info

### ISSUE THREAD

**Issue by TheOddler** [ontehfritz/www.mtgdb.info#63]
When using the GET method to find information it returns irrelevant data. Such as, if you look for an Island, it'll return a json stating the power and toughness are 0. Also, all cards have a Loyalty, regardless of whether or not they're planeswalkers. I don't think this is how it should work.

**Comment by ontehfritz** [comment]
Look at it from the point of view of database table or from a card object those fields or members will always exist.  If I am using C# and deserialize the JSON in general way by having a Card object I will need to have those fields there regardless if they are in the JSON or not. The only benefit from the way you purpose is a slight reduction in JSON output. Going by type and filtering out fields based on that will add maintence issues, as we will have to know the type and fields that are part of the type. 

I am leaving that up to the developer as this can be done on the application side.

**Comment by TheOddler** [comment]
Fair enough. Though I would have thought that those irrelevant fields wouldn't even be in the database for cards that don't use them. This would of course make for a more complicated database, which might not be worth the trouble.
Thanks for explaining!

**Comment by ontehfritz** [comment]
What issue is this causing for you maybe I can help?

**Comment by TheOddler** [comment]
No issues any more. I just got some unexpected data when I implemented the possibility to use this database. Before I used a local database from mtgjson.com. I fixed it by just ignoring the irrelevant data when parsing the json, based on the card-type. But thought I'd report this, just in case it wasn't intended behaviour.

**Comment by ontehfritz** [comment]
:+1:  cool, I will close this. Thanks for the input!
