### ISSUE TITLE
Firefox: Manacost and other mana symbols default to "0" image

### ISSUE THREAD

**Issue by ontehfritz** [ontehfritz/www.mtgdb.info#65]
When viewing manacost or other text that gets rendered with mana symbols etc it renders them the "0" mana symbol. 

Thats F!@ked up!

**Comment by ghost** [comment]
It seems that in firefox background-position-x is not working.
I think that the solution could be background-position: x y
For example using the firefox developer tools:
 background-position: -7em -2em; (Shows mountain in firefox)
Hope it helps

**Comment by ontehfritz** [comment]
Nice man. Thanks for the tip and looking at this for me. Will save me some time when I get to this.

**Comment by ontehfritz** [comment]
@9and3r :+1:  
background-position-x and background-position-y are not implemented as standard in CSS3
