### ISSUE TITLE
Web Design: Update site look and feel

### ISSUE THREAD

**Issue by ontehfritz** [ontehfritz/www.mtgdb.info#8]

**Comment by jesseflorig** [comment]
I'd like to help with this. What exactly are you looking for, a repo of images?

**Comment by ontehfritz** [comment]
I guess I could have rephrased this a bit, but essentially a web designer to skin the site/templates that are bootstrap compatible, custom backgrounds, icons, etc in the magic world atmosphere. Right now it looks very bootstrap-ish.  

I also wanted to have for each set binder a template, icon set, etc to match the theme of that magic set.

**Comment by ontehfritz** [comment]
Closing this as @jesseflorig is powning this. We can create specific issues for any tasks.
